# Set to true to set the time to day when the game starts.
timeSetDayOnStart: true
# Set to true to set the weather to clear when the game starts.
weatherClearOnStart: true
# Set to true to enable nether blocks.
enableNetherBlocks: false
# Set to true to take away OPs for the duration of the game.
takeAwayOps: true
# Set to true to clear players inventories when the game starts.
clearInventories: true
# Set the time to stand on a given block in seconds (60sec - 3600sec)
time: 300