# *********************************************************
# Thank you for using this plugin! <3
# Author: Matistan
# If you enjoy this plugin, please rate it on spigotmc.org:
# https://www.spigotmc.org/resources/block-shuffle.109009/
# *********************************************************

# Set to true to set the time to day automatically when the game starts.
timeSetDayOnStart: true
# Set to true to set the weather to clear automatically when the game starts.
weatherClearOnStart: true
# Set to true to not have to use '/blockshuffle add' every time, and instead play with every player on the server
# (if someone joins in the middle of the game, he will not be playing with everyone)
playWithEveryone: true
# Set to true to enable nether blocks.
enableNetherBlocks: false
# Set to true to take away OPs for the duration of the game.
takeAwayOps: true
# Set to true to clear players inventories when the game starts.
clearInventories: true
# Set the amount of seconds for a round (max 3600sec).
time: 300
# Set to true to make it so that every player has the same block to stand on.
sameBlockForEveryone: false
# Set to true to enable PvP during the match.
pvpEnabled: false
# Set to true to show scoreboard with the timer.
scoreboard: true
# Set to true to enable permission checks.
## Note: This feature needs a permissions plugin (such as LuckPerms) to work.
usePermissions: true
# Set to true to give spectators to players that are no longer in the game.
giveSpectators: true

# *********************
# * GAME MODE OPTIONS *
# *********************

# Set to 0 to play until there is 1 or 0 players left in a game, set to 1 to play until a player has a certain amount of points.
gameMode: 1
# Set the number of point required to win (only if you're playing game mode 1).
pointsToWin: 5
# Set to true to allow only one player to score a point per round (only if you're playing game mode 1).
onlyFirstPoint: false