name: MinecraftBlockShuffle
version: '${project.version}'
main: me.matistan05.minecraftblockshuffle.Main
api-version: 1.16
authors: [ Matistan05 ]
description: If you don't stand on a given block on time, you lose!
commands:
  blockshuffle:
    description: This command sets up the whole blockshuffle game!
    usage: /<command>
permissions:
  blockshuffle.blockshuffle:
    description: Allows the player to use all /blockshuffle commands
    children:
      blockshuffle.add: true
      blockshuffle.remove: true
      blockshuffle.start: true
      blockshuffle.reset: true
      blockshuffle.list: true
      blockshuffle.help: true